[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
auto_detect_solc = false
remappings = [
  "@openzeppelin/=../node_modules/@openzeppelin/",
  "@gluwa/=../node_modules/@gluwa/",
]
allow_paths = ["../node_modules"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
